### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by flema1** [Alvarian/PROJECT-U02#1]
Excellent concept. I think many user world wide could benefit from data about moon phases. Glad we got your "Lune" npm package up and running. Like I mentioned it would be really cool if you could implement some css to display a moon animation that corresponds with the given lune phase.

**Comment by Alvarian** [comment]
CSS is in play and moves simultaneously in par with the object element responsible for indicating the illumination of the moon's phase thanks to our last session. My next step is to use conditions set for illumination to notify the viewer of high tide within their location only if there is a full moon. 

Note to self: After tide notification would be to apply CRUD for user phase.t scheduling, then   authenticating user profile. Lastly styling to completion.
